apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
  namespace: devops
data:
  APP_NAME: Laravel
  APP_ENV: local
  APP_DEBUG: "true"
  APP_URL: http://localhost:8001
  DB_CONNECTION: mysql
  DB_HOST: mysql-service
  DB_PORT: "3306"
  DB_DATABASE: laravel
  DB_USERNAME: sotar
  DB_PASSWORD: sotar123   
  CACHE_DRIVER: file
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: file
